### ISSUE TITLE
Makefiles - Wurzel von 1337 berechnen

### ISSUE THREAD

**Issue by DC4JG** [blinry/nutsh-vorkurs#1]
Ein Student hat den Code aus der Heron.java gelöscht und dafür ganz simpel Math.sqrt(1337) benutzt. Das ist von der Aufgabenstellung her eine gültige Lösung, jedoch entspricht es nicht der Lösungserwartung der Nutsh, weshalb der letzte Dialog in der Lektion nicht getriggert wird.

**Comment by blinry** [comment]
Im Code überprüfe ich, ob die Ausgabe "669.0" enthält – das sollte vor Leuten schützen, die mit `println` einfach die Lösung ausgeben. Andererseits ist das (und auch die Benutzung von `Math.sqrt`) wesentlich mehr Arbeit, als einfach die 42 gegen 1337 auszutauschen. Insofern können wir auch einfach die korrekte Lösung überprüfen :)
